#!/usr/bin/env zsh

# Inspired by ThePrimeagen@github. All credits to him :D
#
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="nvim, alacritty"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Removing $folder"
    stow -D $folder
done
popd
