#!/usr/bin/env zsh

# Inspired by ThePrimeagen@github. All credits to him :D

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Removing $folder"
    stow -D $folder
done
popd
